package mes.domain.mt;

import lombok.Data;

@Data
public class PackingOperInfoVo {
	private String idx;
	private String workOrdNo;
	private String equipCd;
	private String fillSetupWeight;
	private String fillStartSignal;
	private String fillStartYn;
	private String fillSpeed;
	private String fillWeight;
	private String fillOutputCount;
	private String fillPvFrontTemp;
	private String fillSvFrontTemp;
	private String fillPvBackTemp;
	private String fillSvBackTemp;
	private String fillNozzle1OpenTime;
	private String fillNozzle2OpenTime;
	private String fillNozzle3OpenTime;
	private String fillNozzle4OpenTime;
	private String fillDriveStatus;
	private String fillUseYn;
	private String fillErrorBitData;
	private String fillVisionError;
	private String fillPressure;
	private String fillTime;
	private String fillOperStatus;
	private String fillErrorStatus;
	private String fillErrorInfo;
	private String wchkUnderCount;
	private String wchkRqtCount;
	private String wchkOverCount;
	private String wchkNgCount;
	private String wchkExNgCount;
	private String wchkTotalCount;
	private String wchkResult;
	private String wchkCurrWeight;
	private String wchkOperStatus;
	private String wchkAlarmStatus;
	private String capInputCount;
	private String capOutputCount;
	private String capOperStatus;
	private String checkFaultyCount;
	private String capFilmLength;
	private String capUnit;
	private String capDriveStatus;
	private String capUseYn;
	private String capErrorBitData;
	private String capErrorStatus;
	private String capErrorInfo;
	private String boxMoldOperStatus;
	private String boxErrorBitData;
	private String boxErrorBit2Data;
	private String boxMoldDriveStatus;
	private String boxMoldFaulty;
	private String boxErrorStatus;
	private String boxErrorInfo;
	private String deltaRobotOperStatus;
	private String deltaRobotDriveStatus;
	private String boxMarkingOperStatus;
	private String boxMarkingDriveStatus;
	private String articulRobotOperStatus;
	private String articulRobotDriveStatus;
	private String articulRobotOutputCount;
	private String robotErrorBitData;
	private String robotErrorBit2Data;
	private String robotErrorStatus;
	private String robotErrorInfo;
	private String fillUpdateDate;
	private String wchkUpdateDate;
	private String capUpdateDate;
	private String boxUpdateDate;
	private String robotUpdateDate;
	private String updateDate;
	private String regId;
	private String regDate;
	
	private String itemNm;
	private String dtlOrdCnt;
}